
package com.rmaassurance.emissiondirecte.generatedClasses;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IReferentielDevAssBDCWS", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IReferentielDevAssBDCWS {


    /**
     * 
     * @param entiteVO
     * @return
     *     returns generatedClasses.ResultVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRemise", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.CreateRemise")
    @ResponseWrapper(localName = "createRemiseResponse", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.CreateRemiseResponse")
    public ResultVO createRemise(
        @WebParam(name = "entiteVO", targetNamespace = "")
        IEntiteVO entiteVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param mapQuery
     * @return
     *     returns generatedClasses.ResultVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synchroniseDossierSinistreAT", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SynchroniseDossierSinistreAT")
    @ResponseWrapper(localName = "synchroniseDossierSinistreATResponse", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SynchroniseDossierSinistreATResponse")
    public ResultVO synchroniseDossierSinistreAT(
        @WebParam(name = "mapQuery", targetNamespace = "")
        Adapter mapQuery)
        throws Exception_Exception
    ;

    /**
     * 
     * @param dateDebut
     * @param dateFin
     * @param objetVO
     * @return
     *     returns generatedClasses.ResultVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchInfosQtcFromBDC", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SearchInfosQtcFromBDC")
    @ResponseWrapper(localName = "searchInfosQtcFromBDCResponse", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SearchInfosQtcFromBDCResponse")
    public ResultVO searchInfosQtcFromBDC(
        @WebParam(name = "dateDebut", targetNamespace = "")
        String dateDebut,
        @WebParam(name = "dateFin", targetNamespace = "")
        String dateFin,
        @WebParam(name = "objetVO", targetNamespace = "")
        IEntiteVO objetVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param entiteVO
     * @return
     *     returns generatedClasses.ResultVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchRemises", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SearchRemises")
    @ResponseWrapper(localName = "searchRemisesResponse", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SearchRemisesResponse")
    public ResultVO searchRemises(
        @WebParam(name = "entiteVO", targetNamespace = "")
        IEntiteVO entiteVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param objetVO
     * @return
     *     returns generatedClasses.ResultVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchRemisesByNature", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SearchRemisesByNature")
    @ResponseWrapper(localName = "searchRemisesByNatureResponse", targetNamespace = "http://ws.pub.services.referentiel.devass.eai/", className = "generatedClasses.SearchRemisesByNatureResponse")
    public ResultVO searchRemisesByNature(
        @WebParam(name = "objetVO", targetNamespace = "")
        IEntiteVO objetVO)
        throws Exception_Exception
    ;

}
