
package com.rmaassurance.emissiondirecte.generatedClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServiceReferentielDevAssBDCWSService", targetNamespace = "http://ws.impl.services.referentiel.devass.eai/", wsdlLocation = "http://126.7.210.20/REFERENTIEL/services/referentielDevAssBDC?wsdl")
public class ServiceReferentielDevAssBDCWSService
    extends Service
{

    private final static URL SERVICEREFERENTIELDEVASSBDCWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEREFERENTIELDEVASSBDCWSSERVICE_EXCEPTION;
    private final static QName SERVICEREFERENTIELDEVASSBDCWSSERVICE_QNAME = new QName("http://ws.impl.services.referentiel.devass.eai/", "ServiceReferentielDevAssBDCWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://126.7.210.20/REFERENTIEL/services/referentielDevAssBDC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEREFERENTIELDEVASSBDCWSSERVICE_WSDL_LOCATION = url;
        SERVICEREFERENTIELDEVASSBDCWSSERVICE_EXCEPTION = e;
    }

    public ServiceReferentielDevAssBDCWSService() {
        super(__getWsdlLocation(), SERVICEREFERENTIELDEVASSBDCWSSERVICE_QNAME);
    }

    public ServiceReferentielDevAssBDCWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEREFERENTIELDEVASSBDCWSSERVICE_QNAME, features);
    }

    public ServiceReferentielDevAssBDCWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEREFERENTIELDEVASSBDCWSSERVICE_QNAME);
    }

    public ServiceReferentielDevAssBDCWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEREFERENTIELDEVASSBDCWSSERVICE_QNAME, features);
    }

    public ServiceReferentielDevAssBDCWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceReferentielDevAssBDCWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IReferentielDevAssBDCWS
     */
    @WebEndpoint(name = "ServiceReferentielDevAssBDCWSPort")
    public IReferentielDevAssBDCWS getServiceReferentielDevAssBDCWSPort() {
        return super.getPort(new QName("http://ws.impl.services.referentiel.devass.eai/", "ServiceReferentielDevAssBDCWSPort"), IReferentielDevAssBDCWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IReferentielDevAssBDCWS
     */
    @WebEndpoint(name = "ServiceReferentielDevAssBDCWSPort")
    public IReferentielDevAssBDCWS getServiceReferentielDevAssBDCWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.impl.services.referentiel.devass.eai/", "ServiceReferentielDevAssBDCWSPort"), IReferentielDevAssBDCWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEREFERENTIELDEVASSBDCWSSERVICE_EXCEPTION!= null) {
            throw SERVICEREFERENTIELDEVASSBDCWSSERVICE_EXCEPTION;
        }
        return SERVICEREFERENTIELDEVASSBDCWSSERVICE_WSDL_LOCATION;
    }

}
